### ISSUE TITLE
sgt_constructor.py parallelization issues

### ISSUE THREAD

**Issue by robert-ervin-jones** [TheBrownLab/PhyloFisher#19]
After an update to sgt_constructor.py, which added a length filtration checkpoint, the parallelization ability of the script was broken. This resulted in sgt_constructor.py only utilizing one thread.

**Comment by aleixop** [comment]
Hi, thanks for the great tool. Maybe related to this, the fact that sgt_constructor.py runs the snakemake rule in two blocks (from start to length_filter_bmge and then the rest) also creates parallelization issues. Since all BMGE jobs need to finish to proceed with final mafft, several genes that could already be processed are "stuck" until the big genes are done with BMGE. Are you planning on solving this? Thanks again!

**Comment by robert-ervin-jones** [comment]
Hi @aleixop. 

Thanks for the comment. This is something we are aware of and currently working to remedy in v2. v2 will also include the ability to use Snakemake cluster profiles to even better make use of parallelization and resources. I apologize if this has caused you any inconvenience. Just please sit tight and wait for the release of v2!

Thanks,
Robert

**Comment by aleixop** [comment]
Great, thanks!
