### ISSUE TITLE
sgt_constructor.py throws 'No module named 'pandas'' error

### ISSUE THREAD

**Issue by cha-namoth** [TheBrownLab/PhyloFisher#63]
Hi guys,

running into an issue with sgt_constructor.py, where it just outright quits with the following message:

```
ModuleNotFoundError in line 4 of /opt/Anaconda3/envs/fisher/bin/sgt_constructor.smk:
No module named 'pandas'
  File "/opt/Anaconda3/envs/fisher/bin/sgt_constructor.smk", line 4, in <module>
Traceback (most recent call last):
  File "/opt/Anaconda3/envs/fisher/bin/sgt_constructor.py", line 150, in <module>
    run_snakemake(length_filter=False)
  File "/opt/Anaconda3/envs/fisher/bin/sgt_constructor.py", line 85, in run_snakemake
    f'--config {make_config(length_filter)}',
  File "/opt/Anaconda3/envs/fisher/bin/sgt_constructor.py", line 49, in make_config
    f'genes={",".join(get_genes(length_filter))}',
  File "/opt/Anaconda3/envs/fisher/bin/sgt_constructor.py", line 27, in get_genes
    bmge_out_files = [file for file in os.listdir(len_filt_bmge_dir) if file.endswith('.bmge')]
FileNotFoundError: [Errno 2] No such file or directory: '/home/glax/test/Daniele_phylofisher/redo2/sgt_constructor_out_Dec.15.2022/length_filtration/bmge'
```

The commands I ran before were:
```
config.py -d database -i input_metadata.tsv
fisher.py -t 24
informant.py -i fisher_out_Dec.15.2022
working_dataset_constructor.py -i fisher_out_Dec.15.2022
sgt_constructor.py -t 2 -i working_dataset_constructor_out_Dec.15.2022
```

I tried 2 different datasets and it happens on both. `pandas` seems to install if I create a completely fresh conda environment and do `mamba install phylofisher`, so I really don't know what the issue is.

Also I get the same error message when I try phylofisher versions 1.1.2 and 1.2.0. (Currently on version 1.2.3 since 1.2.4 doesn't seem to be available on conda/mamba yet?) So I'm wondering if this even is a phylofisher issue or actually some issue with our server.

Any idea what the issue might be?

Cheers;
Gordon

**Comment by atice** [comment]
Hey Gordon,

I have a few more things I have to get done tonight, but I will take a look first thing in the morning and consult with Rob. Afterwards we will get back to you ASAP. As always thanks for the email.

Alex

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Gordon Lax ***@***.***>
Sent: Thursday, December 15, 2022 7:01:15 PM
To: TheBrownLab/PhyloFisher ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [TheBrownLab/PhyloFisher] sgt_constructor.py throws 'No module named 'pandas'' error (Issue #63)


Hi guys,

running into an issue with sgt_constructor.py, where it just outright quits with the following message:

ModuleNotFoundError in line 4 of /opt/Anaconda3/envs/fisher/bin/sgt_constructor.smk:
No module named 'pandas'
  File "/opt/Anaconda3/envs/fisher/bin/sgt_constructor.smk", line 4, in <module>
Traceback (most recent call last):
  File "/opt/Anaconda3/envs/fisher/bin/sgt_constructor.py", line 150, in <module>
    run_snakemake(length_filter=False)
  File "/opt/Anaconda3/envs/fisher/bin/sgt_constructor.py", line 85, in run_snakemake
    f'--config {make_config(length_filter)}',
  File "/opt/Anaconda3/envs/fisher/bin/sgt_constructor.py", line 49, in make_config
    f'genes={",".join(get_genes(length_filter))}',
  File "/opt/Anaconda3/envs/fisher/bin/sgt_constructor.py", line 27, in get_genes
    bmge_out_files = [file for file in os.listdir(len_filt_bmge_dir) if file.endswith('.bmge')]
FileNotFoundError: [Errno 2] No such file or directory: '/home/glax/test/Daniele_phylofisher/redo2/sgt_constructor_out_Dec.15.2022/length_filtration/bmge'


The commands I ran before were:

config.py -d database -i input_metadata.tsv
fisher.py -t 24
informant.py -i fisher_out_Dec.15.2022
working_dataset_constructor.py -i fisher_out_Dec.15.2022
sgt_constructor.py -t 2 -i working_dataset_constructor_out_Dec.15.2022


I tried 2 different datasets and it happens on both. pandas seems to install if I create a completely fresh conda environment and do mamba install phylofisher, so I really don't know what the issue is.

Also I get the same error message when I try phylofisher versions 1.1.2 and 1.2.0. (Currently on version 1.2.3 since 1.2.4 doesn't seem to be available on conda/mamba yet?) So I'm wondering if this even is a phylofisher issue or actually some issue with our server.

Any idea what the issue might be?

Cheers;
Gordon

**Comment by cha-namoth** [comment]
Thanks Alex – sounds good! (and thanks for timely help as per usual)

**Comment by cha-namoth** [comment]
Hi guys – any news on an update that would fix this issue?

**Comment by atice** [comment]
Hey Gordon,

I’ll look into this tomorrow. Sorry for the delay.

Alex

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by cha-namoth** [comment]
Thanks Alex – and no rush on my part, I just replaced the old sgt_constructor.smk with the updated sgt_constructor.smk in your repository and it seems to work now.

Cheers,
Gordon

**Comment by atice** [comment]
I have a run going that works but I wanted to be thorough before I said anything to you. As always, thanks for sticking with us. We are constantly working to improve the software and add functionality  but sometimes bugs get introduced in doing so. Thanks again.

Alex

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by cha-namoth** [comment]
Absolutely no problem Alex! I'm very happy you guys keep adding new features and fixing bugs. And thanks for making sure it works properly!
