### ISSUE TITLE
Non-reproducible baseline example

### ISSUE THREAD

**Issue by cafernandezlo** [TheBrownLab/PhyloFisher#82]
Hi!

I tried to reproduce the baseline example using the docker image 1.2.8--pyhdfd78af_0 (and others) available at https://bioconda.github.io/recipes/phylofisher/README.html but:

- explore_database.py was able to parse the metadata file
- config.py raise an illegal character error

`docker run -it --rm quay.io/biocontainers/phylofisher:1.2.8--pyhdfd78af_0 /bin/sh
sh-5.0# wget https://ndownloader.figshare.com/files/29093409
Saving to: ‘29093409’

29093409                               100%[============================================================================>]   2.15G  10.2MB/s    in 3m 18s

2023-06-09 08:14:31 (11.1 MB/s) - ‘29093409’ saved [2305051083/2305051083]

sh-5.0# tar -xzf 29093409
sh-5.0# cd PhyloFisherDatabase_v1.0/
sh-5.0# explore_database.py -d database/ -t
 Higher Taxonomy  Organisms
         Alveida          1
       Alveolata         27
       Amoebozoa         42
  Ancyromonadida          4
           CRuMs          4
  Chloroplastida         17
       Cryptista          9
         Discoba         19
     Glaucophyta          4
        Haptista         14
Hemimastigophora          2
  Malawimonadida          3
      Metamonada         10
          Obazoa         49
         Picozoa          1
        Rhizaria         18
    Rhodelphidia          2
      Rhodophyta         15
   Stramenopiles         60
       Telonemia          3
sh-5.0# config.py -d database/ -i database/metadata.tsv
ERROR: illegal character   in Higher Taxonomy`

**Comment by atice** [comment]
Hi!

It looks like you are providing config.py with metadata.tsv instead of the input_metadata.tsv. Check the documentation again for more information. Let us know if this solves the issue.

Alex

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Carlos Fernandez-Lozano ***@***.***>
Sent: Friday, June 9, 2023 3:22:50 AM
To: TheBrownLab/PhyloFisher ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [TheBrownLab/PhyloFisher] Non-reproducible baseline example (Issue #82)


Hi!

I tried to reproduce the baseline example using the docker image 1.2.8--pyhdfd78af_0 (and others) available at https://bioconda.github.io/recipes/phylofisher/README.html<https://secure-web.cisco.com/1lPtm9pb6t_U-NvudOhRs553vV1S_cNciQScyjA9n5M1MdMEX5EYN97Yh0NNk4Wd0UlpuJpHhHCwuh_Cb9nvVonwI2oGr_cZahrU7ityjXYD3T4h7USIbiv4MGXsVkjSZwMPX6wUeEj-bOypiU_nTCLe-sYBOXkcVh69IW36e9aGgbIU7pVj3HytYipQqjZRsn7-6qfJCk_x9xqyyexhu_Z991qUUrSPA21E36ylIkFhms0dWJrjXbtK2gwUgeFyk9_2euqUe5CDu4jUyfo-TC-6yN-a6oXnc9upeF0Q_WkW-fheUp4LSPlVldlGWqf-s/https%3A%2F%2Fbioconda.github.io%2Frecipes%2Fphylofisher%2FREADME.html> but:

  *   explore_database.py was able to parse the metadata file
  *   config.py raise an illegal character error

`docker run -it --rm quay.io/biocontainers/phylofisher:1.2.8--pyhdfd78af_0 /bin/sh
sh-5.0# wget https://ndownloader.figshare.com/files/29093409<https://secure-web.cisco.com/1XrzlyzmYEYRqysT0kiIsDb9jztQCNyCKedWKWSUIlHj87EIXHJCPkssR8_nE_VYLcQTikrjiUuVDCPvnmZgSy3IsauzeW2lIXxyzgNB7Nou4GJC_cHAoDZ7NTNWpE5W8G0PbyRJ-LpAWurJdjlgzyvQNoZws6W9F9IcYead7pBErhR2E5KAJgNfJeF_S79mzhOAf8HutcHAPJkA1EnY02-XK4cEhkMavAjz0xnhLcUu400fG6_TFAJloXA-RLcYIb-nl-XO9KuJvJ2NQ4mbpLZP0XGgiI6Tfu17e9_wb_3BIYuD0UxRtsOEErnPdkRVb/https%3A%2F%2Fndownloader.figshare.com%2Ffiles%2F29093409>
Saving to: ‘29093409’

29093409 100%[============================================================================>] 2.15G 10.2MB/s in 3m 18s

2023-06-09 08:14:31 (11.1 MB/s) - ‘29093409’ saved [2305051083/2305051083]

sh-5.0# tar -xzf 29093409
sh-5.0# cd PhyloFisherDatabase_v1.0/
sh-5.0# explore_database.py -d database/ -t
Higher Taxonomy Organisms
Alveida 1
Alveolata 27
Amoebozoa 42
Ancyromonadida 4
CRuMs 4
Chloroplastida 17
Cryptista 9
Discoba 19
Glaucophyta 4
Haptista 14
Hemimastigophora 2
Malawimonadida 3
Metamonada 10
Obazoa 49
Picozoa 1
Rhizaria 18
Rhodelphidia 2
Rhodophyta 15
Stramenopiles 60
Telonemia 3
sh-5.0# config.py -d database/ -i database/metadata.tsv
ERROR: illegal character in Higher Taxonomy`
